version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fit-control-backend
    depends_on:
      - redis
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - fit-control-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fit-control-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - fit-control-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - fit-control-network

networks:
  fit-control-network:
    driver: bridge
